spring:
  jpa:
    hibernate:
      ddl-auto: drop-and-create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chat_connect
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
