package com.project.chatconnectbackend.controller.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.messaging.handler.annotation.SendTo;
import org.springframework.messaging.simp.SimpMessageHeaderAccessor;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;

import com.project.chatconnectbackend.dto.Chat;
import com.project.chatconnectbackend.dto.MessageDTO;
import com.project.chatconnectbackend.enumValues.ChatStatus;
import com.project.chatconnectbackend.model.User;
import com.project.chatconnectbackend.repository.MessageRepository;

import jakarta.transaction.Transactional;
import java.util.Map;

import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
@Controller
@CrossOrigin(origins = "*")
public class ChatController {

    private static final Logger logger = LoggerFactory.getLogger(ChatController.class);
    @Autowired // This means to get the bean called messageRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MessageRepository messageRepository;

    @MessageMapping("/chat.sendMessage")
    @SendTo("/topic/public")
    @Transactional
    public MessageDTO sendMessage(@Payload @NotNull MessageDTO messageDTO) { // DTO - Data Transfer Object
        if (messageDTO == null) {
            throw new IllegalArgumentException("Message cannot be null");
        }

        logger.info("MessageDTO: " + messageDTO);
        
        Integer sentMessageId= messageRepository.createMessageCustom(
                messageDTO.getMessageText(),
                messageDTO.getFromNumber(),
                messageDTO.getStatus().name(),
                messageDTO.getConversationId());

        messageDTO.setId(sentMessageId);
        return messageDTO;
    }

    @MessageMapping("/chat.addUser")
    @SendTo("/topic/public")
    public Chat addUser(
            @Payload User user,
            SimpMessageHeaderAccessor headerAccessor) {
        logger.info("User joined chat connect: " + user.getId() + " " + user.getFirstName() + " " + user.getLastName());
        Map<String, Object> sessionAttributes = headerAccessor.getSessionAttributes();
        if (sessionAttributes != null) {
            sessionAttributes.put("userId", user.getId());
        }
        Chat chat = new Chat();
        chat.setId(user.getId());
        chat.setLastMessage(null);
        chat.setLastMessageTime(null);
        chat.setName(user.getFirstName() + " " + user.getLastName());
        chat.setProfilePhoto(user.getProfilePhoto());
        chat.setPhoneNumber(user.getPhoneNumber());
        chat.setStatus(ChatStatus.JOIN);
        return chat;
    }
}
